{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "machine_shape": "hm",
      "gpuType": "A100"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "accelerator": "GPU"
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "kdfLpG9VmyD2",
        "outputId": "58894cc2-f9d3-49af-c7cc-e23a66f3b02b"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Cloning into 'ColossalAI'...\n",
            "remote: Enumerating objects: 41584, done.\u001b[K\n",
            "remote: Counting objects: 100% (50/50), done.\u001b[K\n",
            "remote: Compressing objects: 100% (25/25), done.\u001b[K\n",
            "remote: Total 41584 (delta 35), reused 33 (delta 25), pack-reused 41534\u001b[K\n",
            "Receiving objects: 100% (41584/41584), 29.57 MiB | 11.04 MiB/s, done.\n",
            "Resolving deltas: 100% (28490/28490), done.\n"
          ]
        }
      ],
      "source": [
        "! git clone https://github.com/hpcaitech/ColossalAI.git"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "cd ColossalAI/examples/images/vit"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Nn4T8izgngNQ",
        "outputId": "eac151cf-4ee0-41f9-d0c5-059e57c11857"
      },
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "/content/ColossalAI/examples/images/vit\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "! bash run_demo.sh"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "OjiLXWsln7Mg",
        "outputId": "0111a5a8-f74e-4e09-b955-6e777de08047"
      },
      "execution_count": 22,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "+ pip install -r requirements.txt\n",
            "Requirement already satisfied: colossalai>=0.1.12 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 1)) (0.3.6)\n",
            "Requirement already satisfied: torch>=1.8.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 2)) (2.2.1+cu121)\n",
            "Requirement already satisfied: numpy>=1.24.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 3)) (1.25.2)\n",
            "Requirement already satisfied: tqdm>=4.61.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 4)) (4.66.2)\n",
            "Requirement already satisfied: transformers>=4.20.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 5)) (4.38.2)\n",
            "Requirement already satisfied: datasets in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 6)) (2.18.0)\n",
            "Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (5.9.5)\n",
            "Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (24.0)\n",
            "Requirement already satisfied: pre-commit in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (3.7.0)\n",
            "Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (13.7.1)\n",
            "Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (8.1.7)\n",
            "Requirement already satisfied: fabric in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (3.2.2)\n",
            "Requirement already satisfied: contexttimer in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (0.3.3)\n",
            "Requirement already satisfied: ninja in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (1.11.1.1)\n",
            "Requirement already satisfied: safetensors in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (0.4.2)\n",
            "Requirement already satisfied: einops in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (0.7.0)\n",
            "Requirement already satisfied: pydantic in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (2.6.4)\n",
            "Requirement already satisfied: ray in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (2.10.0)\n",
            "Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (0.1.99)\n",
            "Requirement already satisfied: google in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (2.0.3)\n",
            "Requirement already satisfied: protobuf in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (3.20.3)\n",
            "Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (3.13.4)\n",
            "Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (4.11.0)\n",
            "Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (1.12)\n",
            "Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (3.3)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (3.1.3)\n",
            "Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (2023.6.0)\n",
            "Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (12.1.105)\n",
            "Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (12.1.105)\n",
            "Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (12.1.105)\n",
            "Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (8.9.2.26)\n",
            "Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (12.1.3.1)\n",
            "Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (11.0.2.54)\n",
            "Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (10.3.2.106)\n",
            "Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (11.4.5.107)\n",
            "Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (12.1.0.106)\n",
            "Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (2.19.3)\n",
            "Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (12.1.105)\n",
            "Requirement already satisfied: triton==2.2.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (2.2.0)\n",
            "Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.10/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.8.1->-r requirements.txt (line 2)) (12.4.127)\n",
            "Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.20.0->-r requirements.txt (line 5)) (0.20.3)\n",
            "Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.20.0->-r requirements.txt (line 5)) (6.0.1)\n",
            "Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.20.0->-r requirements.txt (line 5)) (2023.12.25)\n",
            "Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers>=4.20.0->-r requirements.txt (line 5)) (2.31.0)\n",
            "Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.20.0->-r requirements.txt (line 5)) (0.15.2)\n",
            "Requirement already satisfied: pyarrow>=12.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements.txt (line 6)) (14.0.2)\n",
            "Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements.txt (line 6)) (0.6)\n",
            "Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements.txt (line 6)) (0.3.8)\n",
            "Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements.txt (line 6)) (2.0.3)\n",
            "Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements.txt (line 6)) (3.4.1)\n",
            "Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements.txt (line 6)) (0.70.16)\n",
            "Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements.txt (line 6)) (3.9.3)\n",
            "Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements.txt (line 6)) (1.3.1)\n",
            "Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements.txt (line 6)) (23.2.0)\n",
            "Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements.txt (line 6)) (1.4.1)\n",
            "Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements.txt (line 6)) (6.0.5)\n",
            "Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements.txt (line 6)) (1.9.4)\n",
            "Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements.txt (line 6)) (4.0.3)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers>=4.20.0->-r requirements.txt (line 5)) (3.3.2)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers>=4.20.0->-r requirements.txt (line 5)) (3.6)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers>=4.20.0->-r requirements.txt (line 5)) (2.0.7)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers>=4.20.0->-r requirements.txt (line 5)) (2024.2.2)\n",
            "Requirement already satisfied: invoke>=2.0 in /usr/local/lib/python3.10/dist-packages (from fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (2.2.0)\n",
            "Requirement already satisfied: paramiko>=2.4 in /usr/local/lib/python3.10/dist-packages (from fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (3.4.0)\n",
            "Requirement already satisfied: decorator>=5 in /usr/local/lib/python3.10/dist-packages (from fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (5.1.1)\n",
            "Requirement already satisfied: deprecated>=1.2 in /usr/local/lib/python3.10/dist-packages (from fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (1.2.14)\n",
            "Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from google->colossalai>=0.1.12->-r requirements.txt (line 1)) (4.12.3)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.8.1->-r requirements.txt (line 2)) (2.1.5)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets->-r requirements.txt (line 6)) (2.8.2)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets->-r requirements.txt (line 6)) (2023.4)\n",
            "Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets->-r requirements.txt (line 6)) (2024.1)\n",
            "Requirement already satisfied: cfgv>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from pre-commit->colossalai>=0.1.12->-r requirements.txt (line 1)) (3.4.0)\n",
            "Requirement already satisfied: identify>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from pre-commit->colossalai>=0.1.12->-r requirements.txt (line 1)) (2.5.35)\n",
            "Requirement already satisfied: nodeenv>=0.11.1 in /usr/local/lib/python3.10/dist-packages (from pre-commit->colossalai>=0.1.12->-r requirements.txt (line 1)) (1.8.0)\n",
            "Requirement already satisfied: virtualenv>=20.10.0 in /usr/local/lib/python3.10/dist-packages (from pre-commit->colossalai>=0.1.12->-r requirements.txt (line 1)) (20.25.1)\n",
            "Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic->colossalai>=0.1.12->-r requirements.txt (line 1)) (0.6.0)\n",
            "Requirement already satisfied: pydantic-core==2.16.3 in /usr/local/lib/python3.10/dist-packages (from pydantic->colossalai>=0.1.12->-r requirements.txt (line 1)) (2.16.3)\n",
            "Requirement already satisfied: jsonschema in /usr/local/lib/python3.10/dist-packages (from ray->colossalai>=0.1.12->-r requirements.txt (line 1)) (4.19.2)\n",
            "Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ray->colossalai>=0.1.12->-r requirements.txt (line 1)) (1.0.8)\n",
            "Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->colossalai>=0.1.12->-r requirements.txt (line 1)) (3.0.0)\n",
            "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->colossalai>=0.1.12->-r requirements.txt (line 1)) (2.16.1)\n",
            "Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.8.1->-r requirements.txt (line 2)) (1.3.0)\n",
            "Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.10/dist-packages (from deprecated>=1.2->fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (1.14.1)\n",
            "Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->colossalai>=0.1.12->-r requirements.txt (line 1)) (0.1.2)\n",
            "Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from nodeenv>=0.11.1->pre-commit->colossalai>=0.1.12->-r requirements.txt (line 1)) (67.7.2)\n",
            "Requirement already satisfied: bcrypt>=3.2 in /usr/local/lib/python3.10/dist-packages (from paramiko>=2.4->fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (4.1.2)\n",
            "Requirement already satisfied: cryptography>=3.3 in /usr/local/lib/python3.10/dist-packages (from paramiko>=2.4->fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (42.0.5)\n",
            "Requirement already satisfied: pynacl>=1.5 in /usr/local/lib/python3.10/dist-packages (from paramiko>=2.4->fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (1.5.0)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets->-r requirements.txt (line 6)) (1.16.0)\n",
            "Requirement already satisfied: distlib<1,>=0.3.7 in /usr/local/lib/python3.10/dist-packages (from virtualenv>=20.10.0->pre-commit->colossalai>=0.1.12->-r requirements.txt (line 1)) (0.3.8)\n",
            "Requirement already satisfied: platformdirs<5,>=3.9.1 in /usr/local/lib/python3.10/dist-packages (from virtualenv>=20.10.0->pre-commit->colossalai>=0.1.12->-r requirements.txt (line 1)) (4.2.0)\n",
            "Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->google->colossalai>=0.1.12->-r requirements.txt (line 1)) (2.5)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema->ray->colossalai>=0.1.12->-r requirements.txt (line 1)) (2023.12.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema->ray->colossalai>=0.1.12->-r requirements.txt (line 1)) (0.34.0)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema->ray->colossalai>=0.1.12->-r requirements.txt (line 1)) (0.18.0)\n",
            "Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.10/dist-packages (from cryptography>=3.3->paramiko>=2.4->fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (1.16.0)\n",
            "Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.12->cryptography>=3.3->paramiko>=2.4->fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (2.22)\n",
            "+ MODEL=google/vit-base-patch16-512\n",
            "+ OUTPUT_PATH=./output_model_1\n",
            "+ PLUGIN=torch_ddp\n",
            "+ TP_SIZE=2\n",
            "+ PP_SIZE=2\n",
            "+ GPUNUM=1\n",
            "+ BS=32\n",
            "+ LR=1e-4\n",
            "+ EPOCH=3\n",
            "+ WEIGHT_DECAY=0.05\n",
            "+ WARMUP_RATIO=0.3\n",
            "+ colossalai run --nproc_per_node 1 --master_port 29505 vit_train_demo.py --model_name_or_path google/vit-base-patch16-512 --output_path ./output_model_1 --plugin torch_ddp --batch_size 32 --tp_size 2 --pp_size 2 --num_epoch 3 --learning_rate 1e-4 --weight_decay 0.05 --warmup_ratio 0.3\n",
            "2024-04-12 13:06:10.111947: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "2024-04-12 13:06:10.111997: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "2024-04-12 13:06:10.113893: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "2024-04-12 13:06:11.297112: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/pipeline/schedule/_utils.py:19: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.\n",
            "  _register_pytree_node(OrderedDict, _odict_flatten, _odict_unflatten)\n",
            "/usr/local/lib/python3.10/dist-packages/torch/utils/_pytree.py:254: UserWarning: <class 'collections.OrderedDict'> is already registered as pytree node. Overwriting the previous registration.\n",
            "  warnings.warn(\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/shardformer/layer/normalization.py:45: UserWarning: Please install apex from source (https://github.com/NVIDIA/apex) to use the fused layernorm kernel\n",
            "  warnings.warn(\"Please install apex from source (https://github.com/NVIDIA/apex) to use the fused layernorm kernel\")\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/initialize.py:48: UserWarning: `config` is deprecated and will be removed soon.\n",
            "  warnings.warn(\"`config` is deprecated and will be removed soon.\")\n",
            "[04/12/24 13:06:13] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /usr/local/lib/python3.10/dist-packages/colossalai/initialize.py:67    \n",
            "                             launch                                                                 \n",
            "                    INFO     colossalai - colossalai - INFO: Distributed environment is initialized,\n",
            "                             world size: 1                                                          \n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py\", line 286, in hf_raise_for_status\n",
            "    response.raise_for_status()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/requests/models.py\", line 1021, in raise_for_status\n",
            "    raise HTTPError(http_error_msg, response=self)\n",
            "requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/google/vit-base-patch16-512/resolve/main/preprocessor_config.json\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py\", line 398, in cached_file\n",
            "    resolved_file = hf_hub_download(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py\", line 118, in _inner_fn\n",
            "    return fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py\", line 1368, in hf_hub_download\n",
            "    raise head_call_error\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py\", line 1238, in hf_hub_download\n",
            "    metadata = get_hf_file_metadata(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py\", line 118, in _inner_fn\n",
            "    return fn(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py\", line 1631, in get_hf_file_metadata\n",
            "    r = _request_wrapper(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py\", line 385, in _request_wrapper\n",
            "    response = _request_wrapper(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py\", line 409, in _request_wrapper\n",
            "    hf_raise_for_status(response)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py\", line 323, in hf_raise_for_status\n",
            "    raise RepositoryNotFoundError(message, response) from e\n",
            "huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-661931c5-56efda703f5d2bf341238225;f0ff7775-1c4a-459a-9dde-f3df07640623)\n",
            "\n",
            "Repository Not Found for url: https://huggingface.co/google/vit-base-patch16-512/resolve/main/preprocessor_config.json.\n",
            "Please make sure you specified the correct `repo_id` and `repo_type`.\n",
            "If you are trying to access a private or gated repo, make sure you are authenticated.\n",
            "Invalid username or password.\n",
            "\n",
            "The above exception was the direct cause of the following exception:\n",
            "\n",
            "Traceback (most recent call last):\n",
            "  File \"/content/ColossalAI/examples/images/vit/vit_train_demo.py\", line 242, in <module>\n",
            "    main()\n",
            "  File \"/content/ColossalAI/examples/images/vit/vit_train_demo.py\", line 158, in main\n",
            "    image_processor = ViTImageProcessor.from_pretrained(args.model_name_or_path)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/transformers/image_processing_utils.py\", line 205, in from_pretrained\n",
            "    image_processor_dict, kwargs = cls.get_image_processor_dict(pretrained_model_name_or_path, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/transformers/image_processing_utils.py\", line 334, in get_image_processor_dict\n",
            "    resolved_image_processor_file = cached_file(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py\", line 421, in cached_file\n",
            "    raise EnvironmentError(\n",
            "OSError: google/vit-base-patch16-512 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'\n",
            "If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`\n",
            "[2024-04-12 13:06:16,900] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 20684) of binary: /usr/bin/python3\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/torchrun\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 347, in wrapper\n",
            "    return f(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py\", line 812, in main\n",
            "    run(args)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py\", line 803, in run\n",
            "    elastic_launch(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py\", line 135, in __call__\n",
            "    return launch_agent(self._config, self._entrypoint, list(args))\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py\", line 268, in launch_agent\n",
            "    raise ChildFailedError(\n",
            "torch.distributed.elastic.multiprocessing.errors.ChildFailedError: \n",
            "============================================================\n",
            "vit_train_demo.py FAILED\n",
            "------------------------------------------------------------\n",
            "Failures:\n",
            "  <NO_OTHER_FAILURES>\n",
            "------------------------------------------------------------\n",
            "Root Cause (first observed failure):\n",
            "[0]:\n",
            "  time      : 2024-04-12_13:06:16\n",
            "  host      : b3b2e2f57c66\n",
            "  rank      : 0 (local_rank: 0)\n",
            "  exitcode  : 1 (pid: 20684)\n",
            "  error_file: <N/A>\n",
            "  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html\n",
            "============================================================\n",
            "Error: failed to run torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr=127.0.0.1 --master_port=29505 vit_train_demo.py --model_name_or_path google/vit-base-patch16-512 --output_path ./output_model_1 --plugin torch_ddp --batch_size 32 --tp_size 2 --pp_size 2 --num_epoch 3 --learning_rate 1e-4 --weight_decay 0.05 --warmup_ratio 0.3 on 127.0.0.1, is localhost: True, exception: Encountered a bad command exit code!\n",
            "\n",
            "Command: 'cd /content/ColossalAI/examples/images/vit && export SHELL=\"/bin/bash\" NV_LIBCUBLAS_VERSION=\"12.2.5.6-1\" NVIDIA_VISIBLE_DEVICES=\"all\" COLAB_JUPYTER_TRANSPORT=\"ipc\" NV_NVML_DEV_VERSION=\"12.2.140-1\" NV_CUDNN_PACKAGE_NAME=\"libcudnn8\" CGROUP_MEMORY_EVENTS=\"/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events\" NV_LIBNCCL_DEV_PACKAGE=\"libnccl-dev=2.19.3-1+cuda12.2\" NV_LIBNCCL_DEV_PACKAGE_VERSION=\"2.19.3-1\" VM_GCE_METADATA_HOST=\"169.254.169.253\" HOSTNAME=\"b3b2e2f57c66\" LANGUAGE=\"en_US\" TBE_RUNTIME_ADDR=\"172.28.0.1:8011\" GCE_METADATA_TIMEOUT=\"3\" NVIDIA_REQUIRE_CUDA=\"cuda>=12.2 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471 brand=tesla,driver>=525,driver<526 brand=unknown,driver>=525,driver<526 brand=nvidia,driver>=525,driver<526 brand=nvidiartx,driver>=525,driver<526 brand=geforce,driver>=525,driver<526 brand=geforcertx,driver>=525,driver<526 brand=quadro,driver>=525,driver<526 brand=quadrortx,driver>=525,driver<526 brand=titan,driver>=525,driver<526 brand=titanrtx,driver>=525,driver<526\" NV_LIBCUBLAS_DEV_PACKAGE=\"libcublas-dev-12-2=12.2.5.6-1\" NV_NVTX_VERSION=\"12.2.140-1\" COLAB_JUPYTER_IP=\"172.28.0.12\" NV_CUDA_CUDART_DEV_VERSION=\"12.2.140-1\" NV_LIBCUSPARSE_VERSION=\"12.1.2.141-1\" COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL=\"http://172.28.0.1:8013/\" NV_LIBNPP_VERSION=\"12.2.1.4-1\" NCCL_VERSION=\"2.19.3-1\" KMP_LISTEN_PORT=\"6000\" TF_FORCE_GPU_ALLOW_GROWTH=\"true\" ENV=\"/root/.bashrc\" PWD=\"/content/ColossalAI/examples/images/vit\" COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT=\"30s\" TBE_EPHEM_CREDS_ADDR=\"172.28.0.1:8009\" TBE_CREDS_ADDR=\"172.28.0.1:8008\" NV_CUDNN_PACKAGE=\"libcudnn8=8.9.6.50-1+cuda12.2\" NVIDIA_DRIVER_CAPABILITIES=\"compute,utility\" LAST_FORCED_REBUILD=\"20240404\" NV_NVPROF_DEV_PACKAGE=\"cuda-nvprof-12-2=12.2.142-1\" NV_LIBNPP_PACKAGE=\"libnpp-12-2=12.2.1.4-1\" NV_LIBNCCL_DEV_PACKAGE_NAME=\"libnccl-dev\" TCLLIBPATH=\"/usr/share/tcltk/tcllib1.20\" NV_LIBCUBLAS_DEV_VERSION=\"12.2.5.6-1\" NVIDIA_PRODUCT_NAME=\"CUDA\" COLAB_KERNEL_MANAGER_PROXY_HOST=\"172.28.0.12\" NV_LIBCUBLAS_DEV_PACKAGE_NAME=\"libcublas-dev-12-2\" USE_AUTH_EPHEM=\"1\" NV_CUDA_CUDART_VERSION=\"12.2.140-1\" COLAB_WARMUP_DEFAULTS=\"1\" HOME=\"/root\" LANG=\"en_US.UTF-8\" COLUMNS=\"100\" CUDA_VERSION=\"12.2.2\" CLOUDSDK_CONFIG=\"/content/.config\" NV_LIBCUBLAS_PACKAGE=\"libcublas-12-2=12.2.5.6-1\" NV_CUDA_NSIGHT_COMPUTE_DEV_PACKAGE=\"cuda-nsight-compute-12-2=12.2.2-1\" COLAB_RELEASE_TAG=\"release-colab_20240410-060226_RC01\" PYDEVD_USE_FRAME_EVAL=\"NO\" KMP_TARGET_PORT=\"9000\" CLICOLOR=\"1\" KMP_EXTRA_ARGS=\"--logtostderr --listen_host=172.28.0.12 --target_host=172.28.0.12 --tunnel_background_save_url=https://colab.research.google.com/tun/m/cc48301118ce562b961b3c22d803539adc1e0c19/gpu-a100-s-1jp3ciyjmcu81 --tunnel_background_save_delay=10s --tunnel_periodic_background_save_frequency=30m0s --enable_output_coalescing=true --output_coalescing_required=true\" NV_LIBNPP_DEV_PACKAGE=\"libnpp-dev-12-2=12.2.1.4-1\" COLAB_LANGUAGE_SERVER_PROXY_LSP_DIRS=\"/datalab/web/pyright/typeshed-fallback/stdlib,/usr/local/lib/python3.10/dist-packages\" NV_LIBCUBLAS_PACKAGE_NAME=\"libcublas-12-2\" COLAB_KERNEL_MANAGER_PROXY_PORT=\"6000\" CLOUDSDK_PYTHON=\"python3\" NV_LIBNPP_DEV_VERSION=\"12.2.1.4-1\" ENABLE_DIRECTORYPREFETCHER=\"1\" NO_GCE_CHECK=\"False\" JPY_PARENT_PID=\"135\" PYTHONPATH=\"/env/python\" TERM=\"xterm-color\" NV_LIBCUSPARSE_DEV_VERSION=\"12.1.2.141-1\" GIT_PAGER=\"cat\" LIBRARY_PATH=\"/usr/local/cuda/lib64/stubs\" NV_CUDNN_VERSION=\"8.9.6.50\" SHLVL=\"1\" PAGER=\"cat\" NV_CUDA_LIB_VERSION=\"12.2.2-1\" COLAB_LANGUAGE_SERVER_PROXY=\"/usr/colab/bin/language_service\" NVARCH=\"x86_64\" NV_CUDNN_PACKAGE_DEV=\"libcudnn8-dev=8.9.6.50-1+cuda12.2\" NV_CUDA_COMPAT_PACKAGE=\"cuda-compat-12-2\" MPLBACKEND=\"module://ipykernel.pylab.backend_inline\" NV_LIBNCCL_PACKAGE=\"libnccl2=2.19.3-1+cuda12.2\" LD_LIBRARY_PATH=\"/usr/lib64-nvidia\" COLAB_GPU=\"1\" NV_CUDA_NSIGHT_COMPUTE_VERSION=\"12.2.2-1\" GCS_READ_CACHE_BLOCK_SIZE_MB=\"16\" NV_NVPROF_VERSION=\"12.2.142-1\" LC_ALL=\"en_US.UTF-8\" COLAB_FILE_HANDLER_ADDR=\"localhost:3453\" PATH=\"/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/google-cloud-sdk/bin\" NV_LIBNCCL_PACKAGE_NAME=\"libnccl2\" COLAB_DEBUG_ADAPTER_MUX_PATH=\"/usr/local/bin/dap_multiplexer\" NV_LIBNCCL_PACKAGE_VERSION=\"2.19.3-1\" PYTHONWARNINGS=\"ignore:::pip._internal.cli.base_command\" DEBIAN_FRONTEND=\"noninteractive\" COLAB_BACKEND_VERSION=\"next\" OLDPWD=\"/\" _=\"/usr/local/bin/colossalai\" && torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr=127.0.0.1 --master_port=29505 vit_train_demo.py --model_name_or_path google/vit-base-patch16-512 --output_path ./output_model_1 --plugin torch_ddp --batch_size 32 --tp_size 2 --pp_size 2 --num_epoch 3 --learning_rate 1e-4 --weight_decay 0.05 --warmup_ratio 0.3'\n",
            "\n",
            "Exit code: 1\n",
            "\n",
            "Stdout: already printed\n",
            "\n",
            "Stderr: already printed\n",
            "\n",
            "\n",
            "\n",
            "====== Training on All Nodes =====\n",
            "127.0.0.1: failure\n",
            "\n",
            "====== Stopping All Nodes =====\n",
            "127.0.0.1: finish\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "! bash run_benchmark.sh"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "cznC-sb0oB9b",
        "outputId": "18581c82-0191-4675-dc97-263edf0fbd31"
      },
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "+ pip install -r requirements.txt\n",
            "Requirement already satisfied: colossalai>=0.1.12 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 1)) (0.3.6)\n",
            "Requirement already satisfied: torch>=1.8.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 2)) (2.2.1+cu121)\n",
            "Requirement already satisfied: numpy>=1.24.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 3)) (1.25.2)\n",
            "Requirement already satisfied: tqdm>=4.61.2 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 4)) (4.66.2)\n",
            "Requirement already satisfied: transformers>=4.20.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 5)) (4.38.2)\n",
            "Requirement already satisfied: datasets in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 6)) (2.18.0)\n",
            "Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (5.9.5)\n",
            "Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (24.0)\n",
            "Requirement already satisfied: pre-commit in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (3.7.0)\n",
            "Requirement already satisfied: rich in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (13.7.1)\n",
            "Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (8.1.7)\n",
            "Requirement already satisfied: fabric in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (3.2.2)\n",
            "Requirement already satisfied: contexttimer in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (0.3.3)\n",
            "Requirement already satisfied: ninja in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (1.11.1.1)\n",
            "Requirement already satisfied: safetensors in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (0.4.2)\n",
            "Requirement already satisfied: einops in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (0.7.0)\n",
            "Requirement already satisfied: pydantic in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (2.6.4)\n",
            "Requirement already satisfied: ray in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (2.10.0)\n",
            "Requirement already satisfied: sentencepiece in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (0.1.99)\n",
            "Requirement already satisfied: google in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (2.0.3)\n",
            "Requirement already satisfied: protobuf in /usr/local/lib/python3.10/dist-packages (from colossalai>=0.1.12->-r requirements.txt (line 1)) (3.20.3)\n",
            "Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (3.13.4)\n",
            "Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (4.11.0)\n",
            "Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (1.12)\n",
            "Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (3.3)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (3.1.3)\n",
            "Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (2023.6.0)\n",
            "Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (12.1.105)\n",
            "Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (12.1.105)\n",
            "Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (12.1.105)\n",
            "Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (8.9.2.26)\n",
            "Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (12.1.3.1)\n",
            "Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (11.0.2.54)\n",
            "Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (10.3.2.106)\n",
            "Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (11.4.5.107)\n",
            "Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (12.1.0.106)\n",
            "Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (2.19.3)\n",
            "Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (12.1.105)\n",
            "Requirement already satisfied: triton==2.2.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.8.1->-r requirements.txt (line 2)) (2.2.0)\n",
            "Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.10/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.8.1->-r requirements.txt (line 2)) (12.4.127)\n",
            "Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.20.0->-r requirements.txt (line 5)) (0.20.3)\n",
            "Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.20.0->-r requirements.txt (line 5)) (6.0.1)\n",
            "Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.20.0->-r requirements.txt (line 5)) (2023.12.25)\n",
            "Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers>=4.20.0->-r requirements.txt (line 5)) (2.31.0)\n",
            "Requirement already satisfied: tokenizers<0.19,>=0.14 in /usr/local/lib/python3.10/dist-packages (from transformers>=4.20.0->-r requirements.txt (line 5)) (0.15.2)\n",
            "Requirement already satisfied: pyarrow>=12.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements.txt (line 6)) (14.0.2)\n",
            "Requirement already satisfied: pyarrow-hotfix in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements.txt (line 6)) (0.6)\n",
            "Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements.txt (line 6)) (0.3.8)\n",
            "Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements.txt (line 6)) (2.0.3)\n",
            "Requirement already satisfied: xxhash in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements.txt (line 6)) (3.4.1)\n",
            "Requirement already satisfied: multiprocess in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements.txt (line 6)) (0.70.16)\n",
            "Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets->-r requirements.txt (line 6)) (3.9.3)\n",
            "Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements.txt (line 6)) (1.3.1)\n",
            "Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements.txt (line 6)) (23.2.0)\n",
            "Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements.txt (line 6)) (1.4.1)\n",
            "Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements.txt (line 6)) (6.0.5)\n",
            "Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements.txt (line 6)) (1.9.4)\n",
            "Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets->-r requirements.txt (line 6)) (4.0.3)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers>=4.20.0->-r requirements.txt (line 5)) (3.3.2)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers>=4.20.0->-r requirements.txt (line 5)) (3.6)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers>=4.20.0->-r requirements.txt (line 5)) (2.0.7)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers>=4.20.0->-r requirements.txt (line 5)) (2024.2.2)\n",
            "Requirement already satisfied: invoke>=2.0 in /usr/local/lib/python3.10/dist-packages (from fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (2.2.0)\n",
            "Requirement already satisfied: paramiko>=2.4 in /usr/local/lib/python3.10/dist-packages (from fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (3.4.0)\n",
            "Requirement already satisfied: decorator>=5 in /usr/local/lib/python3.10/dist-packages (from fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (5.1.1)\n",
            "Requirement already satisfied: deprecated>=1.2 in /usr/local/lib/python3.10/dist-packages (from fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (1.2.14)\n",
            "Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from google->colossalai>=0.1.12->-r requirements.txt (line 1)) (4.12.3)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.8.1->-r requirements.txt (line 2)) (2.1.5)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets->-r requirements.txt (line 6)) (2.8.2)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets->-r requirements.txt (line 6)) (2023.4)\n",
            "Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets->-r requirements.txt (line 6)) (2024.1)\n",
            "Requirement already satisfied: cfgv>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from pre-commit->colossalai>=0.1.12->-r requirements.txt (line 1)) (3.4.0)\n",
            "Requirement already satisfied: identify>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from pre-commit->colossalai>=0.1.12->-r requirements.txt (line 1)) (2.5.35)\n",
            "Requirement already satisfied: nodeenv>=0.11.1 in /usr/local/lib/python3.10/dist-packages (from pre-commit->colossalai>=0.1.12->-r requirements.txt (line 1)) (1.8.0)\n",
            "Requirement already satisfied: virtualenv>=20.10.0 in /usr/local/lib/python3.10/dist-packages (from pre-commit->colossalai>=0.1.12->-r requirements.txt (line 1)) (20.25.1)\n",
            "Requirement already satisfied: annotated-types>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from pydantic->colossalai>=0.1.12->-r requirements.txt (line 1)) (0.6.0)\n",
            "Requirement already satisfied: pydantic-core==2.16.3 in /usr/local/lib/python3.10/dist-packages (from pydantic->colossalai>=0.1.12->-r requirements.txt (line 1)) (2.16.3)\n",
            "Requirement already satisfied: jsonschema in /usr/local/lib/python3.10/dist-packages (from ray->colossalai>=0.1.12->-r requirements.txt (line 1)) (4.19.2)\n",
            "Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ray->colossalai>=0.1.12->-r requirements.txt (line 1)) (1.0.8)\n",
            "Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich->colossalai>=0.1.12->-r requirements.txt (line 1)) (3.0.0)\n",
            "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->colossalai>=0.1.12->-r requirements.txt (line 1)) (2.16.1)\n",
            "Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.8.1->-r requirements.txt (line 2)) (1.3.0)\n",
            "Requirement already satisfied: wrapt<2,>=1.10 in /usr/local/lib/python3.10/dist-packages (from deprecated>=1.2->fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (1.14.1)\n",
            "Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich->colossalai>=0.1.12->-r requirements.txt (line 1)) (0.1.2)\n",
            "Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from nodeenv>=0.11.1->pre-commit->colossalai>=0.1.12->-r requirements.txt (line 1)) (67.7.2)\n",
            "Requirement already satisfied: bcrypt>=3.2 in /usr/local/lib/python3.10/dist-packages (from paramiko>=2.4->fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (4.1.2)\n",
            "Requirement already satisfied: cryptography>=3.3 in /usr/local/lib/python3.10/dist-packages (from paramiko>=2.4->fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (42.0.5)\n",
            "Requirement already satisfied: pynacl>=1.5 in /usr/local/lib/python3.10/dist-packages (from paramiko>=2.4->fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (1.5.0)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets->-r requirements.txt (line 6)) (1.16.0)\n",
            "Requirement already satisfied: distlib<1,>=0.3.7 in /usr/local/lib/python3.10/dist-packages (from virtualenv>=20.10.0->pre-commit->colossalai>=0.1.12->-r requirements.txt (line 1)) (0.3.8)\n",
            "Requirement already satisfied: platformdirs<5,>=3.9.1 in /usr/local/lib/python3.10/dist-packages (from virtualenv>=20.10.0->pre-commit->colossalai>=0.1.12->-r requirements.txt (line 1)) (4.2.0)\n",
            "Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->google->colossalai>=0.1.12->-r requirements.txt (line 1)) (2.5)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.10/dist-packages (from jsonschema->ray->colossalai>=0.1.12->-r requirements.txt (line 1)) (2023.12.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.10/dist-packages (from jsonschema->ray->colossalai>=0.1.12->-r requirements.txt (line 1)) (0.34.0)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from jsonschema->ray->colossalai>=0.1.12->-r requirements.txt (line 1)) (0.18.0)\n",
            "Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.10/dist-packages (from cryptography>=3.3->paramiko>=2.4->fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (1.16.0)\n",
            "Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.12->cryptography>=3.3->paramiko>=2.4->fabric->colossalai>=0.1.12->-r requirements.txt (line 1)) (2.22)\n",
            "+ export BS=8\n",
            "+ BS=8\n",
            "+ export MEMCAP=0\n",
            "+ MEMCAP=0\n",
            "+ export GPUNUM=1\n",
            "+ GPUNUM=1\n",
            "+ for BS in 8 32\n",
            "+ for PLUGIN in \"torch_ddp\" \"torch_ddp_fp16\" \"low_level_zero\" \"gemini\" \"hybrid_parallel\"\n",
            "+ MODEL_PATH=google/vit-base-patch16-224\n",
            "+ colossalai run --nproc_per_node 1 --master_port 29505 vit_benchmark.py --model_name_or_path google/vit-base-patch16-224 --mem_cap 0 --plugin torch_ddp --batch_size 8\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/pipeline/schedule/_utils.py:19: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.\n",
            "  _register_pytree_node(OrderedDict, _odict_flatten, _odict_unflatten)\n",
            "/usr/local/lib/python3.10/dist-packages/torch/utils/_pytree.py:254: UserWarning: <class 'collections.OrderedDict'> is already registered as pytree node. Overwriting the previous registration.\n",
            "  warnings.warn(\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/shardformer/layer/normalization.py:45: UserWarning: Please install apex from source (https://github.com/NVIDIA/apex) to use the fused layernorm kernel\n",
            "  warnings.warn(\"Please install apex from source (https://github.com/NVIDIA/apex) to use the fused layernorm kernel\")\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/initialize.py:48: UserWarning: `config` is deprecated and will be removed soon.\n",
            "  warnings.warn(\"`config` is deprecated and will be removed soon.\")\n",
            "[04/12/24 12:16:29] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /usr/local/lib/python3.10/dist-packages/colossalai/initialize.py:67    \n",
            "                             launch                                                                 \n",
            "                    INFO     colossalai - colossalai - INFO: Distributed environment is initialized,\n",
            "                             world size: 1                                                          \n",
            "[04/12/24 12:16:31] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /content/ColossalAI/examples/images/vit/vit_benchmark.py:68 main       \n",
            "                    INFO     colossalai - colossalai - INFO: Finish loading model from              \n",
            "                             google/vit-base-patch16-224                                            \n",
            "                    INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /content/ColossalAI/examples/images/vit/vit_benchmark.py:94 main       \n",
            "                    INFO     colossalai - colossalai - INFO: Set plugin as torch_ddp                \n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/kernel/extensions/utils.py:96: UserWarning: [extension] The CUDA version on the system (12.2) does not match with the version (12.1) torch was compiled with. The mismatch is found in the minor version. As the APIs are compatible, we will allow compilation to proceed. If you encounter any issue when using the built kernel, please try to build it again with fully matched CUDA versions\n",
            "  warnings.warn(\n",
            "[extension] Compiling the JIT cpu_adam_x86 kernel during runtime now\n",
            "[extension] Time taken to compile cpu_adam_x86 op: 0.0996241569519043 seconds\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/kernel/extensions/utils.py:96: UserWarning: [extension] The CUDA version on the system (12.2) does not match with the version (12.1) torch was compiled with. The mismatch is found in the minor version. As the APIs are compatible, we will allow compilation to proceed. If you encounter any issue when using the built kernel, please try to build it again with fully matched CUDA versions\n",
            "  warnings.warn(\n",
            "[extension] Compiling the JIT fused_optim_cuda kernel during runtime now\n",
            "[extension] Time taken to compile fused_optim_cuda op: 0.11584234237670898 seconds\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/nn/optimizer/hybrid_adam.py:90: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)\n",
            "  self._dummy_overflow_buf = torch.cuda.IntTensor([0])\n",
            "[04/12/24 12:16:32] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /content/ColossalAI/examples/images/vit/vit_benchmark.py:108 main      \n",
            "                    INFO     colossalai - colossalai - INFO: Start testing                          \n",
            "Training Step:   0%|          | 0/20 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/colossalai/nn/optimizer/nvme_optimizer.py:55: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()\n",
            "  numel += p.storage().size()\n",
            "Training Step: 100%|██████████| 20/20 [00:02<00:00,  9.83it/s]\n",
            "[04/12/24 12:16:34] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /content/ColossalAI/examples/images/vit/vit_benchmark.py:138 main      \n",
            "                    INFO     colossalai - colossalai - INFO: Testing finished, batch size per gpu:  \n",
            "                             8, plugin: torch_ddp, throughput: 78.6054, maximum memory usage per    \n",
            "                             gpu: 1.75 GB.                                                          \n",
            "\n",
            "====== Training on All Nodes =====\n",
            "127.0.0.1: success\n",
            "\n",
            "====== Stopping All Nodes =====\n",
            "127.0.0.1: finish\n",
            "+ for PLUGIN in \"torch_ddp\" \"torch_ddp_fp16\" \"low_level_zero\" \"gemini\" \"hybrid_parallel\"\n",
            "+ MODEL_PATH=google/vit-base-patch16-224\n",
            "+ colossalai run --nproc_per_node 1 --master_port 29505 vit_benchmark.py --model_name_or_path google/vit-base-patch16-224 --mem_cap 0 --plugin torch_ddp_fp16 --batch_size 8\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/pipeline/schedule/_utils.py:19: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.\n",
            "  _register_pytree_node(OrderedDict, _odict_flatten, _odict_unflatten)\n",
            "/usr/local/lib/python3.10/dist-packages/torch/utils/_pytree.py:254: UserWarning: <class 'collections.OrderedDict'> is already registered as pytree node. Overwriting the previous registration.\n",
            "  warnings.warn(\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/shardformer/layer/normalization.py:45: UserWarning: Please install apex from source (https://github.com/NVIDIA/apex) to use the fused layernorm kernel\n",
            "  warnings.warn(\"Please install apex from source (https://github.com/NVIDIA/apex) to use the fused layernorm kernel\")\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/initialize.py:48: UserWarning: `config` is deprecated and will be removed soon.\n",
            "  warnings.warn(\"`config` is deprecated and will be removed soon.\")\n",
            "[04/12/24 12:16:43] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /usr/local/lib/python3.10/dist-packages/colossalai/initialize.py:67    \n",
            "                             launch                                                                 \n",
            "                    INFO     colossalai - colossalai - INFO: Distributed environment is initialized,\n",
            "                             world size: 1                                                          \n",
            "[04/12/24 12:16:45] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /content/ColossalAI/examples/images/vit/vit_benchmark.py:68 main       \n",
            "                    INFO     colossalai - colossalai - INFO: Finish loading model from              \n",
            "                             google/vit-base-patch16-224                                            \n",
            "                    INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /content/ColossalAI/examples/images/vit/vit_benchmark.py:94 main       \n",
            "                    INFO     colossalai - colossalai - INFO: Set plugin as torch_ddp_fp16           \n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/kernel/extensions/utils.py:96: UserWarning: [extension] The CUDA version on the system (12.2) does not match with the version (12.1) torch was compiled with. The mismatch is found in the minor version. As the APIs are compatible, we will allow compilation to proceed. If you encounter any issue when using the built kernel, please try to build it again with fully matched CUDA versions\n",
            "  warnings.warn(\n",
            "[extension] Compiling the JIT cpu_adam_x86 kernel during runtime now\n",
            "[extension] Time taken to compile cpu_adam_x86 op: 0.09817695617675781 seconds\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/kernel/extensions/utils.py:96: UserWarning: [extension] The CUDA version on the system (12.2) does not match with the version (12.1) torch was compiled with. The mismatch is found in the minor version. As the APIs are compatible, we will allow compilation to proceed. If you encounter any issue when using the built kernel, please try to build it again with fully matched CUDA versions\n",
            "  warnings.warn(\n",
            "[extension] Compiling the JIT fused_optim_cuda kernel during runtime now\n",
            "[extension] Time taken to compile fused_optim_cuda op: 0.11658954620361328 seconds\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/nn/optimizer/hybrid_adam.py:90: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)\n",
            "  self._dummy_overflow_buf = torch.cuda.IntTensor([0])\n",
            "[04/12/24 12:16:46] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /content/ColossalAI/examples/images/vit/vit_benchmark.py:108 main      \n",
            "                    INFO     colossalai - colossalai - INFO: Start testing                          \n",
            "Training Step:   5%|▌         | 1/20 [00:00<00:08,  2.25it/s]/usr/local/lib/python3.10/dist-packages/colossalai/nn/optimizer/nvme_optimizer.py:55: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()\n",
            "  numel += p.storage().size()\n",
            "Training Step: 100%|██████████| 20/20 [00:01<00:00, 10.74it/s]\n",
            "[04/12/24 12:16:48] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /content/ColossalAI/examples/images/vit/vit_benchmark.py:138 main      \n",
            "                    INFO     colossalai - colossalai - INFO: Testing finished, batch size per gpu:  \n",
            "                             8, plugin: torch_ddp_fp16, throughput: 85.8746, maximum memory usage   \n",
            "                             per gpu: 1.75 GB.                                                      \n",
            "\n",
            "====== Training on All Nodes =====\n",
            "127.0.0.1: success\n",
            "\n",
            "====== Stopping All Nodes =====\n",
            "127.0.0.1: finish\n",
            "+ for PLUGIN in \"torch_ddp\" \"torch_ddp_fp16\" \"low_level_zero\" \"gemini\" \"hybrid_parallel\"\n",
            "+ MODEL_PATH=google/vit-base-patch16-224\n",
            "+ colossalai run --nproc_per_node 1 --master_port 29505 vit_benchmark.py --model_name_or_path google/vit-base-patch16-224 --mem_cap 0 --plugin low_level_zero --batch_size 8\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/pipeline/schedule/_utils.py:19: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.\n",
            "  _register_pytree_node(OrderedDict, _odict_flatten, _odict_unflatten)\n",
            "/usr/local/lib/python3.10/dist-packages/torch/utils/_pytree.py:254: UserWarning: <class 'collections.OrderedDict'> is already registered as pytree node. Overwriting the previous registration.\n",
            "  warnings.warn(\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/shardformer/layer/normalization.py:45: UserWarning: Please install apex from source (https://github.com/NVIDIA/apex) to use the fused layernorm kernel\n",
            "  warnings.warn(\"Please install apex from source (https://github.com/NVIDIA/apex) to use the fused layernorm kernel\")\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/initialize.py:48: UserWarning: `config` is deprecated and will be removed soon.\n",
            "  warnings.warn(\"`config` is deprecated and will be removed soon.\")\n",
            "[04/12/24 12:16:57] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /usr/local/lib/python3.10/dist-packages/colossalai/initialize.py:67    \n",
            "                             launch                                                                 \n",
            "                    INFO     colossalai - colossalai - INFO: Distributed environment is initialized,\n",
            "                             world size: 1                                                          \n",
            "[04/12/24 12:16:59] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /content/ColossalAI/examples/images/vit/vit_benchmark.py:68 main       \n",
            "                    INFO     colossalai - colossalai - INFO: Finish loading model from              \n",
            "                             google/vit-base-patch16-224                                            \n",
            "                    INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /content/ColossalAI/examples/images/vit/vit_benchmark.py:94 main       \n",
            "                    INFO     colossalai - colossalai - INFO: Set plugin as low_level_zero           \n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/kernel/extensions/utils.py:96: UserWarning: [extension] The CUDA version on the system (12.2) does not match with the version (12.1) torch was compiled with. The mismatch is found in the minor version. As the APIs are compatible, we will allow compilation to proceed. If you encounter any issue when using the built kernel, please try to build it again with fully matched CUDA versions\n",
            "  warnings.warn(\n",
            "[extension] Compiling the JIT cpu_adam_x86 kernel during runtime now\n",
            "[extension] Time taken to compile cpu_adam_x86 op: 0.09799075126647949 seconds\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/kernel/extensions/utils.py:96: UserWarning: [extension] The CUDA version on the system (12.2) does not match with the version (12.1) torch was compiled with. The mismatch is found in the minor version. As the APIs are compatible, we will allow compilation to proceed. If you encounter any issue when using the built kernel, please try to build it again with fully matched CUDA versions\n",
            "  warnings.warn(\n",
            "[extension] Compiling the JIT fused_optim_cuda kernel during runtime now\n",
            "[extension] Time taken to compile fused_optim_cuda op: 0.11626505851745605 seconds\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/nn/optimizer/hybrid_adam.py:90: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)\n",
            "  self._dummy_overflow_buf = torch.cuda.IntTensor([0])\n",
            "[04/12/24 12:17:00] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /content/ColossalAI/examples/images/vit/vit_benchmark.py:108 main      \n",
            "                    INFO     colossalai - colossalai - INFO: Start testing                          \n",
            "Training Step:   0%|          | 0/20 [00:00<?, ?it/s]/usr/local/lib/python3.10/dist-packages/colossalai/nn/optimizer/nvme_optimizer.py:55: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()\n",
            "  numel += p.storage().size()\n",
            "Training Step: 100%|██████████| 20/20 [00:03<00:00,  5.80it/s]\n",
            "[04/12/24 12:17:03] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /content/ColossalAI/examples/images/vit/vit_benchmark.py:138 main      \n",
            "                    INFO     colossalai - colossalai - INFO: Testing finished, batch size per gpu:  \n",
            "                             8, plugin: low_level_zero, throughput: 46.3693, maximum memory usage   \n",
            "                             per gpu: 1.66 GB.                                                      \n",
            "\n",
            "====== Training on All Nodes =====\n",
            "127.0.0.1: success\n",
            "\n",
            "====== Stopping All Nodes =====\n",
            "127.0.0.1: finish\n",
            "+ for PLUGIN in \"torch_ddp\" \"torch_ddp_fp16\" \"low_level_zero\" \"gemini\" \"hybrid_parallel\"\n",
            "+ MODEL_PATH=google/vit-base-patch16-224\n",
            "+ colossalai run --nproc_per_node 1 --master_port 29505 vit_benchmark.py --model_name_or_path google/vit-base-patch16-224 --mem_cap 0 --plugin gemini --batch_size 8\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/pipeline/schedule/_utils.py:19: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.\n",
            "  _register_pytree_node(OrderedDict, _odict_flatten, _odict_unflatten)\n",
            "/usr/local/lib/python3.10/dist-packages/torch/utils/_pytree.py:254: UserWarning: <class 'collections.OrderedDict'> is already registered as pytree node. Overwriting the previous registration.\n",
            "  warnings.warn(\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/shardformer/layer/normalization.py:45: UserWarning: Please install apex from source (https://github.com/NVIDIA/apex) to use the fused layernorm kernel\n",
            "  warnings.warn(\"Please install apex from source (https://github.com/NVIDIA/apex) to use the fused layernorm kernel\")\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/initialize.py:48: UserWarning: `config` is deprecated and will be removed soon.\n",
            "  warnings.warn(\"`config` is deprecated and will be removed soon.\")\n",
            "[04/12/24 12:17:16] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /usr/local/lib/python3.10/dist-packages/colossalai/initialize.py:67    \n",
            "                             launch                                                                 \n",
            "                    INFO     colossalai - colossalai - INFO: Distributed environment is initialized,\n",
            "                             world size: 1                                                          \n",
            "[04/12/24 12:17:18] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /content/ColossalAI/examples/images/vit/vit_benchmark.py:68 main       \n",
            "                    INFO     colossalai - colossalai - INFO: Finish loading model from              \n",
            "                             google/vit-base-patch16-224                                            \n",
            "                    INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /content/ColossalAI/examples/images/vit/vit_benchmark.py:94 main       \n",
            "                    INFO     colossalai - colossalai - INFO: Set plugin as gemini                   \n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/kernel/extensions/utils.py:96: UserWarning: [extension] The CUDA version on the system (12.2) does not match with the version (12.1) torch was compiled with. The mismatch is found in the minor version. As the APIs are compatible, we will allow compilation to proceed. If you encounter any issue when using the built kernel, please try to build it again with fully matched CUDA versions\n",
            "  warnings.warn(\n",
            "[extension] Compiling the JIT cpu_adam_x86 kernel during runtime now\n",
            "[extension] Time taken to compile cpu_adam_x86 op: 0.09902215003967285 seconds\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/kernel/extensions/utils.py:96: UserWarning: [extension] The CUDA version on the system (12.2) does not match with the version (12.1) torch was compiled with. The mismatch is found in the minor version. As the APIs are compatible, we will allow compilation to proceed. If you encounter any issue when using the built kernel, please try to build it again with fully matched CUDA versions\n",
            "  warnings.warn(\n",
            "[extension] Compiling the JIT fused_optim_cuda kernel during runtime now\n",
            "[extension] Time taken to compile fused_optim_cuda op: 0.11883187294006348 seconds\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/nn/optimizer/hybrid_adam.py:90: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)\n",
            "  self._dummy_overflow_buf = torch.cuda.IntTensor([0])\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/zero/gemini/chunk/chunk.py:45: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()\n",
            "  return tensor.storage().size() == 0\n",
            "[04/12/24 12:17:20] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /content/ColossalAI/examples/images/vit/vit_benchmark.py:108 main      \n",
            "                    INFO     colossalai - colossalai - INFO: Start testing                          \n",
            "Training Step: 100%|██████████| 20/20 [00:04<00:00,  4.18it/s]\n",
            "[04/12/24 12:17:25] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /content/ColossalAI/examples/images/vit/vit_benchmark.py:138 main      \n",
            "                    INFO     colossalai - colossalai - INFO: Testing finished, batch size per gpu:  \n",
            "                             8, plugin: gemini, throughput: 33.4621, maximum memory usage per gpu:  \n",
            "                             663.17 MB.                                                             \n",
            "\n",
            "====== Training on All Nodes =====\n",
            "127.0.0.1: success\n",
            "\n",
            "====== Stopping All Nodes =====\n",
            "127.0.0.1: finish\n",
            "+ for PLUGIN in \"torch_ddp\" \"torch_ddp_fp16\" \"low_level_zero\" \"gemini\" \"hybrid_parallel\"\n",
            "+ MODEL_PATH=google/vit-base-patch16-224\n",
            "+ colossalai run --nproc_per_node 1 --master_port 29505 vit_benchmark.py --model_name_or_path google/vit-base-patch16-224 --mem_cap 0 --plugin hybrid_parallel --batch_size 8\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/pipeline/schedule/_utils.py:19: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.\n",
            "  _register_pytree_node(OrderedDict, _odict_flatten, _odict_unflatten)\n",
            "/usr/local/lib/python3.10/dist-packages/torch/utils/_pytree.py:254: UserWarning: <class 'collections.OrderedDict'> is already registered as pytree node. Overwriting the previous registration.\n",
            "  warnings.warn(\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/shardformer/layer/normalization.py:45: UserWarning: Please install apex from source (https://github.com/NVIDIA/apex) to use the fused layernorm kernel\n",
            "  warnings.warn(\"Please install apex from source (https://github.com/NVIDIA/apex) to use the fused layernorm kernel\")\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/initialize.py:48: UserWarning: `config` is deprecated and will be removed soon.\n",
            "  warnings.warn(\"`config` is deprecated and will be removed soon.\")\n",
            "[04/12/24 12:17:35] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /usr/local/lib/python3.10/dist-packages/colossalai/initialize.py:67    \n",
            "                             launch                                                                 \n",
            "                    INFO     colossalai - colossalai - INFO: Distributed environment is initialized,\n",
            "                             world size: 1                                                          \n",
            "[04/12/24 12:17:37] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /content/ColossalAI/examples/images/vit/vit_benchmark.py:68 main       \n",
            "                    INFO     colossalai - colossalai - INFO: Finish loading model from              \n",
            "                             google/vit-base-patch16-224                                            \n",
            "Traceback (most recent call last):\n",
            "  File \"/content/ColossalAI/examples/images/vit/vit_benchmark.py\", line 151, in <module>\n",
            "    main()\n",
            "  File \"/content/ColossalAI/examples/images/vit/vit_benchmark.py\", line 85, in main\n",
            "    plugin = HybridParallelPlugin(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/colossalai/booster/plugin/hybrid_parallel_plugin.py\", line 969, in __init__\n",
            "    dist.get_world_size() % (tp_size * pp_size) == 0\n",
            "AssertionError: world size 1 is not divisible by tp_size 2 * pp_size 2\n",
            "Exception ignored in: <function HybridParallelPlugin.__del__ at 0x7c88dc1d4b80>\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/colossalai/booster/plugin/hybrid_parallel_plugin.py\", line 1071, in __del__\n",
            "    self.pg_mesh.destroy_mesh_process_groups()\n",
            "AttributeError: 'HybridParallelPlugin' object has no attribute 'pg_mesh'\n",
            "[2024-04-12 12:17:42,323] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 5587) of binary: /usr/bin/python3\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/torchrun\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 347, in wrapper\n",
            "    return f(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py\", line 812, in main\n",
            "    run(args)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py\", line 803, in run\n",
            "    elastic_launch(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py\", line 135, in __call__\n",
            "    return launch_agent(self._config, self._entrypoint, list(args))\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py\", line 268, in launch_agent\n",
            "    raise ChildFailedError(\n",
            "torch.distributed.elastic.multiprocessing.errors.ChildFailedError: \n",
            "============================================================\n",
            "vit_benchmark.py FAILED\n",
            "------------------------------------------------------------\n",
            "Failures:\n",
            "  <NO_OTHER_FAILURES>\n",
            "------------------------------------------------------------\n",
            "Root Cause (first observed failure):\n",
            "[0]:\n",
            "  time      : 2024-04-12_12:17:42\n",
            "  host      : b3b2e2f57c66\n",
            "  rank      : 0 (local_rank: 0)\n",
            "  exitcode  : 1 (pid: 5587)\n",
            "  error_file: <N/A>\n",
            "  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html\n",
            "============================================================\n",
            "Error: failed to run torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr=127.0.0.1 --master_port=29505 vit_benchmark.py --model_name_or_path google/vit-base-patch16-224 --mem_cap 0 --plugin hybrid_parallel --batch_size 8 on 127.0.0.1, is localhost: True, exception: Encountered a bad command exit code!\n",
            "\n",
            "Command: 'cd /content/ColossalAI/examples/images/vit && export SHELL=\"/bin/bash\" NV_LIBCUBLAS_VERSION=\"12.2.5.6-1\" NVIDIA_VISIBLE_DEVICES=\"all\" COLAB_JUPYTER_TRANSPORT=\"ipc\" NV_NVML_DEV_VERSION=\"12.2.140-1\" NV_CUDNN_PACKAGE_NAME=\"libcudnn8\" CGROUP_MEMORY_EVENTS=\"/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events\" GPUNUM=\"1\" NV_LIBNCCL_DEV_PACKAGE=\"libnccl-dev=2.19.3-1+cuda12.2\" NV_LIBNCCL_DEV_PACKAGE_VERSION=\"2.19.3-1\" VM_GCE_METADATA_HOST=\"169.254.169.253\" HOSTNAME=\"b3b2e2f57c66\" LANGUAGE=\"en_US\" TBE_RUNTIME_ADDR=\"172.28.0.1:8011\" GCE_METADATA_TIMEOUT=\"3\" NVIDIA_REQUIRE_CUDA=\"cuda>=12.2 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471 brand=tesla,driver>=525,driver<526 brand=unknown,driver>=525,driver<526 brand=nvidia,driver>=525,driver<526 brand=nvidiartx,driver>=525,driver<526 brand=geforce,driver>=525,driver<526 brand=geforcertx,driver>=525,driver<526 brand=quadro,driver>=525,driver<526 brand=quadrortx,driver>=525,driver<526 brand=titan,driver>=525,driver<526 brand=titanrtx,driver>=525,driver<526\" NV_LIBCUBLAS_DEV_PACKAGE=\"libcublas-dev-12-2=12.2.5.6-1\" NV_NVTX_VERSION=\"12.2.140-1\" COLAB_JUPYTER_IP=\"172.28.0.12\" NV_CUDA_CUDART_DEV_VERSION=\"12.2.140-1\" NV_LIBCUSPARSE_VERSION=\"12.1.2.141-1\" COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL=\"http://172.28.0.1:8013/\" NV_LIBNPP_VERSION=\"12.2.1.4-1\" NCCL_VERSION=\"2.19.3-1\" KMP_LISTEN_PORT=\"6000\" TF_FORCE_GPU_ALLOW_GROWTH=\"true\" ENV=\"/root/.bashrc\" PWD=\"/content/ColossalAI/examples/images/vit\" COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT=\"30s\" TBE_EPHEM_CREDS_ADDR=\"172.28.0.1:8009\" TBE_CREDS_ADDR=\"172.28.0.1:8008\" NV_CUDNN_PACKAGE=\"libcudnn8=8.9.6.50-1+cuda12.2\" NVIDIA_DRIVER_CAPABILITIES=\"compute,utility\" LAST_FORCED_REBUILD=\"20240404\" NV_NVPROF_DEV_PACKAGE=\"cuda-nvprof-12-2=12.2.142-1\" NV_LIBNPP_PACKAGE=\"libnpp-12-2=12.2.1.4-1\" NV_LIBNCCL_DEV_PACKAGE_NAME=\"libnccl-dev\" BS=\"8\" TCLLIBPATH=\"/usr/share/tcltk/tcllib1.20\" NV_LIBCUBLAS_DEV_VERSION=\"12.2.5.6-1\" NVIDIA_PRODUCT_NAME=\"CUDA\" COLAB_KERNEL_MANAGER_PROXY_HOST=\"172.28.0.12\" NV_LIBCUBLAS_DEV_PACKAGE_NAME=\"libcublas-dev-12-2\" USE_AUTH_EPHEM=\"1\" NV_CUDA_CUDART_VERSION=\"12.2.140-1\" COLAB_WARMUP_DEFAULTS=\"1\" HOME=\"/root\" LANG=\"en_US.UTF-8\" COLUMNS=\"100\" CUDA_VERSION=\"12.2.2\" CLOUDSDK_CONFIG=\"/content/.config\" NV_LIBCUBLAS_PACKAGE=\"libcublas-12-2=12.2.5.6-1\" NV_CUDA_NSIGHT_COMPUTE_DEV_PACKAGE=\"cuda-nsight-compute-12-2=12.2.2-1\" COLAB_RELEASE_TAG=\"release-colab_20240410-060226_RC01\" PYDEVD_USE_FRAME_EVAL=\"NO\" KMP_TARGET_PORT=\"9000\" CLICOLOR=\"1\" KMP_EXTRA_ARGS=\"--logtostderr --listen_host=172.28.0.12 --target_host=172.28.0.12 --tunnel_background_save_url=https://colab.research.google.com/tun/m/cc48301118ce562b961b3c22d803539adc1e0c19/gpu-a100-s-1jp3ciyjmcu81 --tunnel_background_save_delay=10s --tunnel_periodic_background_save_frequency=30m0s --enable_output_coalescing=true --output_coalescing_required=true\" NV_LIBNPP_DEV_PACKAGE=\"libnpp-dev-12-2=12.2.1.4-1\" COLAB_LANGUAGE_SERVER_PROXY_LSP_DIRS=\"/datalab/web/pyright/typeshed-fallback/stdlib,/usr/local/lib/python3.10/dist-packages\" NV_LIBCUBLAS_PACKAGE_NAME=\"libcublas-12-2\" COLAB_KERNEL_MANAGER_PROXY_PORT=\"6000\" CLOUDSDK_PYTHON=\"python3\" NV_LIBNPP_DEV_VERSION=\"12.2.1.4-1\" ENABLE_DIRECTORYPREFETCHER=\"1\" NO_GCE_CHECK=\"False\" JPY_PARENT_PID=\"135\" PYTHONPATH=\"/env/python\" TERM=\"xterm-color\" NV_LIBCUSPARSE_DEV_VERSION=\"12.1.2.141-1\" GIT_PAGER=\"cat\" LIBRARY_PATH=\"/usr/local/cuda/lib64/stubs\" NV_CUDNN_VERSION=\"8.9.6.50\" SHLVL=\"1\" PAGER=\"cat\" NV_CUDA_LIB_VERSION=\"12.2.2-1\" COLAB_LANGUAGE_SERVER_PROXY=\"/usr/colab/bin/language_service\" NVARCH=\"x86_64\" NV_CUDNN_PACKAGE_DEV=\"libcudnn8-dev=8.9.6.50-1+cuda12.2\" NV_CUDA_COMPAT_PACKAGE=\"cuda-compat-12-2\" MPLBACKEND=\"module://ipykernel.pylab.backend_inline\" NV_LIBNCCL_PACKAGE=\"libnccl2=2.19.3-1+cuda12.2\" LD_LIBRARY_PATH=\"/usr/lib64-nvidia\" MEMCAP=\"0\" COLAB_GPU=\"1\" NV_CUDA_NSIGHT_COMPUTE_VERSION=\"12.2.2-1\" GCS_READ_CACHE_BLOCK_SIZE_MB=\"16\" NV_NVPROF_VERSION=\"12.2.142-1\" LC_ALL=\"en_US.UTF-8\" COLAB_FILE_HANDLER_ADDR=\"localhost:3453\" PATH=\"/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/google-cloud-sdk/bin\" NV_LIBNCCL_PACKAGE_NAME=\"libnccl2\" COLAB_DEBUG_ADAPTER_MUX_PATH=\"/usr/local/bin/dap_multiplexer\" NV_LIBNCCL_PACKAGE_VERSION=\"2.19.3-1\" PYTHONWARNINGS=\"ignore:::pip._internal.cli.base_command\" DEBIAN_FRONTEND=\"noninteractive\" COLAB_BACKEND_VERSION=\"next\" OLDPWD=\"/\" _=\"/usr/local/bin/colossalai\" && torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr=127.0.0.1 --master_port=29505 vit_benchmark.py --model_name_or_path google/vit-base-patch16-224 --mem_cap 0 --plugin hybrid_parallel --batch_size 8'\n",
            "\n",
            "Exit code: 1\n",
            "\n",
            "Stdout: already printed\n",
            "\n",
            "Stderr: already printed\n",
            "\n",
            "\n",
            "\n",
            "====== Training on All Nodes =====\n",
            "127.0.0.1: failure\n",
            "\n",
            "====== Stopping All Nodes =====\n",
            "127.0.0.1: finish\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "pIMJqE7Ao3Tr",
        "outputId": "c08a3598-6586-4b5b-c2f5-419eacef59c1"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/pipeline/schedule/_utils.py:19: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.\n",
            "  _register_pytree_node(OrderedDict, _odict_flatten, _odict_unflatten)\n",
            "/usr/local/lib/python3.10/dist-packages/torch/utils/_pytree.py:254: UserWarning: <class 'collections.OrderedDict'> is already registered as pytree node. Overwriting the previous registration.\n",
            "  warnings.warn(\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/shardformer/layer/normalization.py:45: UserWarning: Please install apex from source (https://github.com/NVIDIA/apex) to use the fused layernorm kernel\n",
            "  warnings.warn(\"Please install apex from source (https://github.com/NVIDIA/apex) to use the fused layernorm kernel\")\n",
            "/usr/local/lib/python3.10/dist-packages/colossalai/initialize.py:48: UserWarning: `config` is deprecated and will be removed soon.\n",
            "  warnings.warn(\"`config` is deprecated and will be removed soon.\")\n",
            "[04/12/24 09:29:56] INFO     colossalai - colossalai - INFO:                                        \n",
            "                             /usr/local/lib/python3.10/dist-packages/colossalai/initialize.py:67    \n",
            "                             launch                                                                 \n",
            "                    INFO     colossalai - colossalai - INFO: Distributed environment is initialized,\n",
            "                             world size: 1                                                          \n",
            "Files already downloaded and verified\n",
            "Files already downloaded and verified\n",
            "Traceback (most recent call last):\n",
            "  File \"/content/train.py\", line 207, in <module>\n",
            "    main()\n",
            "  File \"/content/train.py\", line 167, in main\n",
            "    optimizer = HybridAdam(model.parameters(), lr=LEARNING_RATE)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/colossalai/nn/optimizer/hybrid_adam.py\", line 76, in __init__\n",
            "    super().__init__(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/colossalai/nn/optimizer/cpu_adam.py\", line 80, in __init__\n",
            "    cpu_adam = CPUAdamLoader().load()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/colossalai/kernel/kernel_loader.py\", line 73, in load\n",
            "    assert len(usable_exts) != 0, f\"No usable kernel found for {self.__class__.__name__} on the current machine.\"\n",
            "AssertionError: No usable kernel found for CPUAdamLoader on the current machine.\n",
            "[2024-04-12 09:30:04,661] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 2724) of binary: /usr/bin/python3\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/torchrun\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 347, in wrapper\n",
            "    return f(*args, **kwargs)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py\", line 812, in main\n",
            "    run(args)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py\", line 803, in run\n",
            "    elastic_launch(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py\", line 135, in __call__\n",
            "    return launch_agent(self._config, self._entrypoint, list(args))\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py\", line 268, in launch_agent\n",
            "    raise ChildFailedError(\n",
            "torch.distributed.elastic.multiprocessing.errors.ChildFailedError: \n",
            "============================================================\n",
            "train.py FAILED\n",
            "------------------------------------------------------------\n",
            "Failures:\n",
            "  <NO_OTHER_FAILURES>\n",
            "------------------------------------------------------------\n",
            "Root Cause (first observed failure):\n",
            "[0]:\n",
            "  time      : 2024-04-12_09:30:04\n",
            "  host      : bfb5fe6ae8c4\n",
            "  rank      : 0 (local_rank: 0)\n",
            "  exitcode  : 1 (pid: 2724)\n",
            "  error_file: <N/A>\n",
            "  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html\n",
            "============================================================\n",
            "Error: failed to run torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr=127.0.0.1 --master_port=29500 train.py -c ./ckpt-fp32 on 127.0.0.1, is localhost: True, exception: Encountered a bad command exit code!\n",
            "\n",
            "Command: 'cd /content && export SHELL=\"/bin/bash\" NV_LIBCUBLAS_VERSION=\"12.2.5.6-1\" NVIDIA_VISIBLE_DEVICES=\"all\" COLAB_JUPYTER_TRANSPORT=\"ipc\" NV_NVML_DEV_VERSION=\"12.2.140-1\" NV_CUDNN_PACKAGE_NAME=\"libcudnn8\" CGROUP_MEMORY_EVENTS=\"/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events\" NV_LIBNCCL_DEV_PACKAGE=\"libnccl-dev=2.19.3-1+cuda12.2\" NV_LIBNCCL_DEV_PACKAGE_VERSION=\"2.19.3-1\" VM_GCE_METADATA_HOST=\"169.254.169.253\" HOSTNAME=\"bfb5fe6ae8c4\" LANGUAGE=\"en_US\" TBE_RUNTIME_ADDR=\"172.28.0.1:8011\" GCE_METADATA_TIMEOUT=\"3\" NVIDIA_REQUIRE_CUDA=\"cuda>=12.2 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471 brand=tesla,driver>=525,driver<526 brand=unknown,driver>=525,driver<526 brand=nvidia,driver>=525,driver<526 brand=nvidiartx,driver>=525,driver<526 brand=geforce,driver>=525,driver<526 brand=geforcertx,driver>=525,driver<526 brand=quadro,driver>=525,driver<526 brand=quadrortx,driver>=525,driver<526 brand=titan,driver>=525,driver<526 brand=titanrtx,driver>=525,driver<526\" NV_LIBCUBLAS_DEV_PACKAGE=\"libcublas-dev-12-2=12.2.5.6-1\" NV_NVTX_VERSION=\"12.2.140-1\" COLAB_JUPYTER_IP=\"172.28.0.12\" NV_CUDA_CUDART_DEV_VERSION=\"12.2.140-1\" NV_LIBCUSPARSE_VERSION=\"12.1.2.141-1\" COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL=\"http://172.28.0.1:8013/\" NV_LIBNPP_VERSION=\"12.2.1.4-1\" NCCL_VERSION=\"2.19.3-1\" KMP_LISTEN_PORT=\"6000\" TF_FORCE_GPU_ALLOW_GROWTH=\"true\" ENV=\"/root/.bashrc\" PWD=\"/content\" COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT=\"30s\" TBE_EPHEM_CREDS_ADDR=\"172.28.0.1:8009\" TBE_CREDS_ADDR=\"172.28.0.1:8008\" NV_CUDNN_PACKAGE=\"libcudnn8=8.9.6.50-1+cuda12.2\" NVIDIA_DRIVER_CAPABILITIES=\"compute,utility\" LAST_FORCED_REBUILD=\"20240404\" NV_NVPROF_DEV_PACKAGE=\"cuda-nvprof-12-2=12.2.142-1\" NV_LIBNPP_PACKAGE=\"libnpp-12-2=12.2.1.4-1\" NV_LIBNCCL_DEV_PACKAGE_NAME=\"libnccl-dev\" TCLLIBPATH=\"/usr/share/tcltk/tcllib1.20\" NV_LIBCUBLAS_DEV_VERSION=\"12.2.5.6-1\" COLAB_KERNEL_MANAGER_PROXY_HOST=\"172.28.0.12\" NVIDIA_PRODUCT_NAME=\"CUDA\" NV_LIBCUBLAS_DEV_PACKAGE_NAME=\"libcublas-dev-12-2\" USE_AUTH_EPHEM=\"1\" NV_CUDA_CUDART_VERSION=\"12.2.140-1\" COLAB_WARMUP_DEFAULTS=\"1\" HOME=\"/root\" LANG=\"en_US.UTF-8\" COLUMNS=\"100\" CUDA_VERSION=\"12.2.2\" CLOUDSDK_CONFIG=\"/content/.config\" NV_LIBCUBLAS_PACKAGE=\"libcublas-12-2=12.2.5.6-1\" NV_CUDA_NSIGHT_COMPUTE_DEV_PACKAGE=\"cuda-nsight-compute-12-2=12.2.2-1\" COLAB_RELEASE_TAG=\"release-colab_20240410-060226_RC01\" PYDEVD_USE_FRAME_EVAL=\"NO\" KMP_TARGET_PORT=\"9000\" CLICOLOR=\"1\" KMP_EXTRA_ARGS=\"--logtostderr --listen_host=172.28.0.12 --target_host=172.28.0.12 --tunnel_background_save_url=https://colab.research.google.com/tun/m/cc48301118ce562b961b3c22d803539adc1e0c19/m-s-3ue2mjp5swcdn --tunnel_background_save_delay=10s --tunnel_periodic_background_save_frequency=30m0s --enable_output_coalescing=true --output_coalescing_required=true\" NV_LIBNPP_DEV_PACKAGE=\"libnpp-dev-12-2=12.2.1.4-1\" COLAB_LANGUAGE_SERVER_PROXY_LSP_DIRS=\"/datalab/web/pyright/typeshed-fallback/stdlib,/usr/local/lib/python3.10/dist-packages\" NV_LIBCUBLAS_PACKAGE_NAME=\"libcublas-12-2\" COLAB_KERNEL_MANAGER_PROXY_PORT=\"6000\" CLOUDSDK_PYTHON=\"python3\" NV_LIBNPP_DEV_VERSION=\"12.2.1.4-1\" ENABLE_DIRECTORYPREFETCHER=\"1\" NO_GCE_CHECK=\"False\" JPY_PARENT_PID=\"85\" PYTHONPATH=\"/env/python\" TERM=\"xterm-color\" NV_LIBCUSPARSE_DEV_VERSION=\"12.1.2.141-1\" GIT_PAGER=\"cat\" LIBRARY_PATH=\"/usr/local/cuda/lib64/stubs\" NV_CUDNN_VERSION=\"8.9.6.50\" SHLVL=\"0\" PAGER=\"cat\" COLAB_LANGUAGE_SERVER_PROXY=\"/usr/colab/bin/language_service\" NV_CUDA_LIB_VERSION=\"12.2.2-1\" NVARCH=\"x86_64\" NV_CUDNN_PACKAGE_DEV=\"libcudnn8-dev=8.9.6.50-1+cuda12.2\" NV_CUDA_COMPAT_PACKAGE=\"cuda-compat-12-2\" MPLBACKEND=\"module://ipykernel.pylab.backend_inline\" NV_LIBNCCL_PACKAGE=\"libnccl2=2.19.3-1+cuda12.2\" LD_LIBRARY_PATH=\"/usr/local/nvidia/lib:/usr/local/nvidia/lib64\" GCS_READ_CACHE_BLOCK_SIZE_MB=\"16\" NV_CUDA_NSIGHT_COMPUTE_VERSION=\"12.2.2-1\" NV_NVPROF_VERSION=\"12.2.142-1\" LC_ALL=\"en_US.UTF-8\" COLAB_FILE_HANDLER_ADDR=\"localhost:3453\" PATH=\"/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/google-cloud-sdk/bin\" NV_LIBNCCL_PACKAGE_NAME=\"libnccl2\" COLAB_DEBUG_ADAPTER_MUX_PATH=\"/usr/local/bin/dap_multiplexer\" NV_LIBNCCL_PACKAGE_VERSION=\"2.19.3-1\" PYTHONWARNINGS=\"ignore:::pip._internal.cli.base_command\" DEBIAN_FRONTEND=\"noninteractive\" COLAB_BACKEND_VERSION=\"next\" OLDPWD=\"/\" _=\"/usr/local/bin/colossalai\" && torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --master_addr=127.0.0.1 --master_port=29500 train.py -c ./ckpt-fp32'\n",
            "\n",
            "Exit code: 1\n",
            "\n",
            "Stdout: already printed\n",
            "\n",
            "Stderr: already printed\n",
            "\n",
            "\n",
            "\n",
            "====== Training on All Nodes =====\n",
            "127.0.0.1: failure\n",
            "\n",
            "====== Stopping All Nodes =====\n",
            "127.0.0.1: finish\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "bash test_ci.sh"
      ],
      "metadata": {
        "id": "f_DBXJRfMqgK"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "bash benchmark.sh"
      ],
      "metadata": {
        "id": "W3vSTnfuMrYY"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}